# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- task: PowerShell@2
  displayName: Hello World
  inputs:
    filePath: "$(System.DefaultWorkingDirectory)/Hello World/Execute-HelloWorld.ps1"
