trigger:
- none

pool:
  vmImage: ubuntu-latest

jobs:
- job: 'psScriptAnalyzer'
  displayName: PSScriptAnalyzer
  steps:
    - task: PowerShell@2
      displayName: Analyse PowerShell
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      inputs:
        arguments: '-ScriptDirectory $(Build.Repository.LocalPath)/branch-policies/deploymentFiles'
        filePath: $(Build.Repository.LocalPath)/branch-policies/supportFiles/validation-psscriptanalyzer.ps1
        pwsh: true
        targetType: filepath
